Extension: Practitioner_qualification_status
Id: practitioner-qualification-status
Description: "An indicator of the practicing status of the practitioner as supplied by their Responsible Authority or professional body."
//These files were generated by a script from a model at HpiPractitioner.qualification.status

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/qualificationStatus (preferred)