Extension: Nzethnicity
Id: nzethnicity
Description: "Self-identified ethnicity of the person."
//These files were generated by a script from a model at HpiPractitioner.ethnicity

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/valueset/ethnic-group-level-4 (preferred)