Extension: nzethnicity
Id: nzethnicity
Description:  "None supplied yet"
//These files were generated by a script

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/valueset/ethnic-group-level-4 (preferred)