Extension: Practitioner_deathdate
Id: practitioner-deathdate
Description: "The date the person died."
//These files were generated by a script from a model at HpiPractitioner.deathDate

* extension 0..0
* value[x] only date