Extension: patient-iwi
Id: patient-iwi
Description:  "None supplied yet"
//These files were generated by a script

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/nziwi (preferred)