Extension: practitioner-qualification-initialDate
Id: practitioner-qualification-initialDate
Description:  "None supplied yet"
//These files were generated by a script

* extension 0..0
* value[x] only date