Extension: geolocation
Id: geolocation
Description:  "None supplied yet"
//These files were generated by a script

* extension contains
    latitude 0..1

// definitions of sub-extensions
* extension[latitude].url = "latitude"
* extension[latitude] ^definition = "No description"
* extension[latitude].value[x] only decimal
