Extension: Location_alias_type
Id: location-alias-type
Description: "Indicates the type of alias name"
//These files were generated by a script from a model at HpiLocation.alias.type

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/location-alias-type (preferred)