Extension: NzGeocode
Id: nzGeocode
Description: "A geocode that uses the NZ datum (rather than the one specified for .position) We are currently unable to convert to WGS84"
//These files were generated by a script from a model at HpiLocation.geoCode

* extension contains
    latitude 1..1

// definitions of sub-extensions
* extension[latitude].url = "latitude"
* extension[latitude] ^definition = "No description"
* extension[latitude].value[x] only decimal
