Extension: Geolocation
Id: geolocation
Description: "The geolocation of the address. datum = NZVD2016"
//These files were generated by a script from a model at NzNHIPatient.address.geoLocation

* extension contains
    latitude 0..1

// definitions of sub-extensions
* extension[latitude].url = "latitude"
* extension[latitude] ^definition = "No description"
* extension[latitude].value[x] only decimal
