Extension: hpiLocation-establishedExt
Id: hpiLocation-established
Description: "The period over which the location is open"
//These files were generated by a script

* extension 0..0
* value[x] only Period