Extension: HpiLocation_dhb
Id: hpiLocation-dhb
Description: "The District Health Board where this facility is located"
//These files were generated by a script from a model at HpiLocation.DHB

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/dhb (preferred)