Extension: Registration_initial_date
Id: registration-initial-date
Description: "The date the practitioner first became registered with the Responsible Authority or professional body"
//These files were generated by a script from a model at HpiPractitioner.qualification.initialDate

* extension 0..0
* value[x] only date