Extension: Organization_period
Id: organization-period
Description: "The period over which the Organization is active"
//These files were generated by a script from a model at HpiOrganization.established

* extension 0..0
* value[x] only Period