Extension: Organization_aliasType
Id: organization-aliasType
Description: "eg abbreviated, maori..."
//These files were generated by a script from a model at HpiOrganization.alias.type

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/organization-alias-type (preferred)