Extension: Location_aliasType
Id: location-aliasType
Description: "Indicates the type of alias name"
//These files were generated by a script from a model at HpiLocation.alias.aliasType

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/aliasType (preferred)