Extension: HpiLocation_established
Id: hpiLocation-established
Description: "The period over which the location is open"
//These files were generated by a script from a model at HpiLocation.established

* extension 0..0
* value[x] only Period